

# Author: Mazhar Ahmed, CTO, Oceanize Inc
# All rights reserved. Copyright (c) Oceanize Inc
version: '3'
services:
  app_dns:
    image: oceanize/flask_app:latest
    container_name: flask_app_xss
    restart: unless-stopped
    labels:
      project: "flask"
      day: "9 Sep 2019"
    build:
      # build the image from Dockerfile
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      # bind on our 5000 port because most people have 80, 8080 already bound
      - "80:80"